parameters:
    contact.form.type.message.class: KPhoen\ContactBundle\Form\Type\MessageType

services:
    contact.form.type.message:
        class: '%contact.form.type.message.class%'
        tags:
            - { name: form.type, alias: contact_message }
