---
contact:
    path: /contact
    defaults: {_controller: "KPhoenContactBundle:Contact:contact"}

contact_send:
    path: /contact/send
    defaults: {_controller: "KPhoenContactBundle:Contact:contact"}
    requirements:
        _method: POST
