contact:
    pattern:   /contact
    defaults:  { _controller: KPhoenContactBundle:Contact:contact }

contact_send:
    pattern:   /contact/send
    defaults:  { _controller: KPhoenContactBundle:Contact:contact }
    requirements:
        _method:  POST
