---
language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update

install:
  - composer install --prefer-source

script: ./vendor/bin/phpunit

notifications:
  email: false
