language: php

sudo: false

php:
    - 5.5
    - 5.6
    - 7.0

before_install:
    - phpenv config-rm xdebug.ini || true
    - composer self-update

install:
    - composer install --prefer-source

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit -c ./phpunit.xml.dist

after_script:
  - ./vendor/bin/coveralls -v

notifications:
    email: false
