language: php

sudo: false

php:
    - 7.0

before_install:
    - composer self-update

install:
    - composer install --prefer-source

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - travis_retry php vendor/bin/coveralls -v

notifications:
    email: false
